name: Build and test
on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  build-cuda:
    name: Build and test (CUDA, ${{ matrix.target }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: ubuntu
            runs_on: '["linux", "cuda"]'
          - target: windows
            runs_on: '["windows", "cuda"]'
    runs-on: ${{ fromJson(matrix.runs_on) }}
    defaults:
      run:
        shell: bash
    env:
      TMPDIR: ${{ github.workspace }}/.tmp
      PYTHONUTF8: "1"
    steps:

    - name: checkout code
      uses: actions/checkout@v4

    - name: prepare tmp
      run: |
        mkdir -p "$TMPDIR"

    - name: check preinstalled toolchain
      run: |
        command -v python
        command -v pip
        command -v xmake
        command -v nvcc
        python --version
        pip --version
        xmake --version
        nvidia-smi
        nvcc --version

    - name: Xmake CUDA Build & Install
      run: |
        xmake f --nv-gpu=y -c -v
        xmake -v
        xmake install
    
    - name: Install Python
      run: | 
        cd python
        pip install ./llaisyscore/
        pip install ./server-project/
        cd ..

    - name: CUDA runtime api test
      run: |
        python test/test_runtime.py --device nvidia

    - name: CUDA ops tests
      run: |
        python test/ops/add.py --device nvidia
        python test/ops/argmax.py --device nvidia
        python test/ops/embedding.py --device nvidia
        python test/ops/linear.py --device nvidia
        python test/ops/random_sample.py --device nvidia
        python test/ops/rms_norm.py --device nvidia
        python test/ops/rope.py --device nvidia
        python test/ops/self_attention.py --device nvidia
        python test/ops/swiglu.py --device nvidia

    - name: CUDA infer test
      run: |
        python test/test_infer.py --device nvidia --test
      
